#!/usr/bin/env python3
"""Builds the shell's embedded fonts.

  tools/gen-fonts.py [--inter PATH/InterVariable.ttf] [--hack PATH/Hack-Regular.ttf]

With source paths, re-creates Resources/Fonts/*.ttf (static Inter instances and a Hack
subset, Latin-1 plus a few symbols, hinting removed). Without them, only regenerates
src/Gui/Graphics/EmbeddedFonts.g.cs from the existing Resources/Fonts/*.ttf.
Requires fonttools (pip install fonttools).
"""
import argparse
import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "Resources" / "Fonts"
OUTPUT = ROOT / "src" / "Gui" / "Graphics" / "EmbeddedFonts.g.cs"

LATIN = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100))
PUNCT = [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x2190, 0x2191, 0x2192, 0x2193]
BOX = [0x2500, 0x2502, 0x250C, 0x2510, 0x2514, 0x2518, 0x251C, 0x2524, 0x2588, 0x2591, 0x2592]

EMBEDDED = [("InterRegular", "Inter-Regular"), ("InterSemiBold", "Inter-SemiBold"), ("HackRegular", "Hack-Regular")]


def subset_font(font, unicodes):
    from fontTools import subset

    opts = subset.Options()
    opts.hinting = False
    opts.layout_features = []
    opts.notdef_outline = True
    opts.name_IDs = [0, 1, 2, 4, 5, 6, 13, 14]
    opts.drop_tables += ["GPOS", "GSUB", "GDEF", "STAT", "DSIG", "kern"]
    subsetter = subset.Subsetter(opts)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)


def build_inter(path):
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer

    for name, weight in (("Regular", 400), ("SemiBold", 600)):
        font = TTFont(path)
        axes = {a.axisTag: (weight if a.axisTag == "wght" else a.defaultValue) for a in font["fvar"].axes}
        font = instancer.instantiateVariableFont(font, axes)
        subset_font(font, LATIN + PUNCT + [0xD7])
        font.save(FONTS / f"Inter-{name}.ttf")


def build_hack(path):
    from fontTools.ttLib import TTFont

    font = TTFont(path)
    subset_font(font, LATIN + PUNCT + BOX)
    font.save(FONTS / "Hack-Regular.ttf")


def write_csharp():
    lines = [
        "// <auto-generated>",
        "// Inter (https://rsms.me/inter) by Rasmus Andersson, SIL Open Font License 1.1.",
        "// Hack (https://sourcefoundry.org/hack/), MIT License + Bitstream Vera License.",
        "// Subset to Latin-1 (+ a few symbols). Source files: Resources/Fonts/*.ttf.",
        "// Regenerate with tools/gen-fonts.py; do not edit by hand.",
        "// </auto-generated>",
        "",
        "namespace MyOS.Gui.Graphics;",
        "",
        "internal static class EmbeddedFonts",
        "{",
    ]
    for field, file in EMBEDDED:
        data = base64.b64encode((FONTS / f"{file}.ttf").read_bytes()).decode()
        chunks = [data[i:i + 120] for i in range(0, len(data), 120)]
        lines.append(f"    public const string {field} =")
        lines += [f'        "{c}"' + (" +" if i < len(chunks) - 1 else ";") for i, c in enumerate(chunks)]
        lines.append("")
    lines[-1] = "}"
    OUTPUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--inter", help="path to InterVariable.ttf")
    parser.add_argument("--hack", help="path to Hack-Regular.ttf")
    args = parser.parse_args()
    if args.inter:
        build_inter(args.inter)
    if args.hack:
        build_hack(args.hack)
    write_csharp()
